### ISSUE TITLE
Watering can desync

### ISSUE THREAD

**Issue by Darkere** [WTBW-Mods/WTBW#2]
The watering can seems to tick clientside as well causing ghost growth that goes away on blockupdate. 

**Version** : wtbw-1.15.1-1.0.2
**Forge** : 1.15-30.0.30
**Pack** :  [Randomly Added Mods](https://www.curseforge.com/minecraft/modpacks/randomly-added-mods)

**Comment by Naxanria** [comment]
Fixed in 1.15.1-1.0.3
